# Generated by Django 5.0.2 on 2025-08-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='growthrecord',
            table='plant_growthrecord',
        ),
    ]
