# Generated by Django 5.0.2 on 2025-07-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration_type',
            field=models.CharField(choices=[('once', '一次性'), ('daily', '每日'), ('weekly', '每周')], default='once', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('work', '工作'), ('life', '生活'), ('study', '学习')], default='work', max_length=20),
        ),
    ]
