# Generated by Django 5.0.2 on 2025-07-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_title_task_plant_remove_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='plant',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
